setting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'))
]

user/urls.py
from django.urls import path

from user import views

app_name='user'
urlpatterns = [
    path('', views.home, name='home'),

    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.Signup.as_view(), name='register'),
    
    path('profile/', views.profile, name='profile'),
    path('update/', views.ChangeInfo.as_view(), name='update'),
    path('reset-password/', views.ResetPass.as_view(), name='reset-pass'),
    path('reset-password-done/', views.PassChangeDone.as_view(), name='change_done'),
]

user/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager # root of Users classes
from django.contrib.auth.models import User, AbstractUser, UserManager, PermissionsMixin # ***

#### usable package in them
from django.contrib.auth import password_validation
from django.contrib.auth.hashers import (
    check_password,
    is_password_usable,
    make_password,
)


'''
########### Build-in model for authentication and permission


## 1 - <AbstractBaseUser> 
        fields : 
            - password
            - last_login
        property :
            - is_authenticated
            - is_anonymous
            - ...
        methods:
            - set_password
            - get_email_field_name
            - ...

    --> this model use attrs :
        - REQUIRED_FIELDS
        - USERNAME_FIELD
        - EMAIL_FIELD
################################

## 2 - <AbstractUser> (AbstractBaseUser, PermissionsMixin)
        fields:
            - username
            - email
            - is_staff
            - ...
        methods:
            - email_user
            - ...
        
    --> this model use <UserManager>
################################


## 3 - User (AbstractUser) :  Users within the Django authentication system are represented by this
    model.  
###############################


## 4 - <PermissionsMixin>
        fields:
            - is_superuser
            - groups
            - user_permissions
        methods:
            - get_user_permissions(obj=None)
            - get_group_permissions
            - has_perm(perm)
            - has_perms(perm_list)
    
    --> permission = <app_name>.<model_name>.<create, update, delete, retreive>
##############################


'''

user/forms.py
from django.contrib.auth.forms import \
    AuthenticationForm, \
    UserCreationForm, UserChangeForm, \
    SetPasswordForm, PasswordChangeForm, PasswordResetForm


'''
------------------------- AUTHENTICATION -------------------------
------------------------------------------------------------------
## AuthenticationForm :
    fields:
        - username
        - password
    methods:
        - get_user


------------------------- REGISTRATION -------------------------
----------------------------------------------------------------
## 1 - UserCreationForm :
    fields:
        - username
        - password1
        - password2
########################

## 2 - UserChangeForm : 
    fields:
        - __all__ (of the User model)
        - password : ReadOnlyPasswordHashField
########################

------------------------- RESET PASSWORD -----------------------
----------------------------------------------------------------
## 1 - SetPasswordForm(user):
    fields:
        - new_password1
        - new_password2
############################

## 2 - PasswordChangeForm(user):
    fields:
        - old_password
        - new_password1
        - new_password2
############################

## 3 - PasswordResetForm:
    fields:
        - email
    --> reset password with send email to user
############################

## 4 - AdminPasswordChangeForm :
    - A form used to change the password of a user in the admin interface.
############################


'''

user/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView

# Create your views here.
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm


from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.views import \
    LoginView, LogoutView, logout_then_login, redirect_to_login, \
    PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView


from django.contrib.auth.decorators import login_required


def home(request):
    return render(request, 'user/home.html')


'''
------------------ AUTHENTICATION ----------------------
--------------------------------------------------------

########## usable function for login and logout 
    1 - login(request)
    2 - logout(request)
    3 - authenticate(request) :
        - If the given credentials are valid, return a User object.

    4 - logout_then_login(login_url) : 
        - Log out the user if they are logged in. Then redirect to the login page.
        - use settings.LOGIN_URL of login_url

    5 - redirect_to_login(login_url) : 
        - Redirect the user to the login page, passing the given 'next' page.
###############################################


## 1 - LoginView :
        attrs :
            - form_class = AuthenticationForm
            - authentication_form = None
            - next_page = None
            - redirect_field_name = REDIRECT_FIELD_NAME
            - template_name = "registration/login.html"
            - redirect_authenticated_user = False
            - extra_context = None
        methods:
            - get_success_url
            - get_redirect_url
            - form_valid
            - get_default_redirect_url

    ---> use function <login(request, user)> to login in <form_valid> method
    ---> use settings.LOGIN_REDIRECT_URL in <get_default_redirect_url>
##################

## 2 - LogoutView :
        attrs:
            - next_page = None
            - redirect_field_name = REDIRECT_FIELD_NAME
            - template_name = "registration/logged_out.html"
            - extra_context = None
        methods:
            - get_next_page
            - get_context_data
    ---> use settings.LOGOUT_REDIRECT_URL in <get_next_page>

##################
'''

class CustomLoginView(LoginView):
    template_name = 'user/login.html' # default: "registration/login.html"
    redirect_authenticated_user = True # redirect to get_success_url(self)

    # define the default url in setting.LOGIN_REDIRECT_URL
    # def get_success_url(self):
    #     return reverse_lazy('user:profile')

class CustomLogoutView(LogoutView):
    next_page = 'user:home'





'''
------------------------- REGISTRATION -------------------------
----------------------------------------------------------------

#### for registration purpose never view is given.
#### but exist all required form for managing views (forms.py)

----------------------------------------------------------------
----------------------------------------------------------------
'''


class Signup(CreateView):
    form_class = UserCreationForm
    template_name = 'user/register.html'

    # for redirect authenticated user
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("user:profile")
        return super(Signup, self).get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('user:profile')

class ChangeInfo(UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = 'user/update.html'

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('user:profile')



'''
------------------------- RESET PASSWORD -------------------------
------------------------------------------------------------------

# - PasswordResetView sends the mail
# - PasswordResetDoneView shows a success message for the above
# - PasswordResetConfirmView checks the link the user clicked and
#   prompts for a new password
# - PasswordResetCompleteView shows a success message for the above

## 1 - PasswordChangeView
## 2 - PasswordChangeDoneView
------------------------------------------------------------------
------------------------------------------------------------------
'''


class ResetPass(PasswordChangeView):
    template_name = 'user/reset_pass.html'     
    success_url = reverse_lazy("user:change_done")

class PassChangeDone(PasswordChangeDoneView):
    template_name = 'user/pass_change_done.html'

    def dispatch(self, request, *args, **kwargs):
        # logout(request)
        return super().dispatch(request, *args, **kwargs)
    
    

@login_required(login_url='user:login')
def profile(request):
    return render(request, 'user/profile.html')

user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django tutorial</title>
</head>

<body>
    
    {% block content %}{% endblock content %}

</body>
</html>

user/templates/user/home.html
{% extends 'user/base.html' %}

{% block content %}

<main>
    <h2>Welcom to my django tutorial: <strong>AUTHENTICATION AND AUTHORIZATION</strong> build-in system</h2>
    <a href="{% url 'user:login' %}">login</a>
</main>

{% endblock content %}

user/templates/user/login.html
{% extends 'user/base.html' %}


{% block content %}

<main>
    <h2>LOGIN PAGE</h2>
</main>

<div>
    <form method="POST">
        {% csrf_token %}
        <div>
            <label for="id_username">Username:</label>
            <input type="text" name="username" autofocus maxlength="150" required>
        </div>
        
        <div>
            <label for="id_password">Password:</label>
            <input type="password" name="password" required>
        </div>

        {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
        {% endif %}

        <input type="submit" value="login" />

        <h5>you have not an account : <a href="{% url 'user:register' %}">signup</a></h5>
    </form>
</div>

{% endblock content %}

user/templates/user/pass_change_done.html
{% extends 'user/base.html' %}


{% block content %}

<h2>Your password updated successfuly !!</h2>
<a href="{% url 'user:login' %}"> LOGIN </a>

{% endblock content %}

user/templates/user/profile.html
{% extends 'user/base.html' %}

{% block content %}

<h1>You are a authentication user</h1>
<h3><a href="{% url 'user:logout' %}">logout</a></h3>
<h3><a href="{% url 'user:update' %}">update</a></h3>

{% endblock content %}

user/templates/user/register.html
{% extends 'user/base.html' %}

{% block content %}

<main>
    <h2>REGISTER PAGE</h2>
</main>
<div>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register">
    </form>
</div>
<div>
    <p>Already have an account? <a href="{% url 'user:login'%}">Login</a></p>
</div>

{% endblock content %}

user/templates/user/reset_pass.html
{% extends 'user/base.html' %}


{% block content %}

<main>
    <h2>RESET PASSWORD PAGE</h2>
</main>
<div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="save">
    </form>
</div>


{% endblock content %}

user/templates/user/update.html
{% extends 'user/base.html' %}

{% block content %}

<h3>Update your informations</h3>
<div>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="save">
    </form>
</div>
<div>
    <h2><a href="{% url 'user:reset-pass'%}">reset password</a></h2>
</div>

{% endblock content %}